// ─── Datos de escrituras — Arena Nexus S.L. ──────────────────────────────────
// 7 activos inmobiliarios + holding. No se prevén más compras.

export const ESCRITURAS = {
  BB5: {
    nombre: "Barrera de Baix 5",
    ciudad: "Palma",
    fecha_firma: "30/07/2025",
    notaria: "Luis López de Paz (Paseo Castellana 172, Madrid)",
    protocolo: "577",
    vendedor: "María del Pilar Sánchez Trullas",
    precio: 180000,
    ref_catastral: "8903212DD6880D0002MK / 8903212DD6880D0004WB",
    valor_catastral: 170208.80,
    superficie_m2: 49,
    anio_construccion: 1910,
    estado: "Ocupada ilegalmente",
    cargas: "Libre de cargas",
  },
  FMM3: {
    nombre: "Francesc Martí Mora 3",
    ciudad: "Palma",
    fecha_firma: "28/07/2025",
    notaria: "Blanca Valenzuela Fernández",
    protocolo: "2214",
    vendedor: "PROMONTORIA COLISEUM RESIDENTIAL, S.L.",
    precio: 180000,
    ref_catastral: "9112101DD6891C0172FD",
    valor_catastral: 161428.21,
    superficie_m2: 86,
    anio_construccion: 1968,
    estado: "Ocupada ilegalmente",
    cargas: "Libre de cargas",
  },
  PR30: {
    nombre: "Pascual Ribot 30",
    ciudad: "Palma",
    fecha_firma: "28/07/2025",
    notaria: "Blanca Valenzuela Fernández",
    protocolo: "2221",
    vendedor: "PROMONTORIA COLISEUM REAL ESTATE, S.L.U.",
    precio: 205000,
    ref_catastral: "8814109DD6881D0022SE",
    valor_catastral: null,
    superficie_m2: 92.76,
    anio_construccion: null,
    estado: "Ocupada en precario",
    cargas: "Libre de cargas",
  },
  PB27: {
    nombre: "Pau Bouvy 27",
    ciudad: "Palma",
    fecha_firma: "17/10/2025",
    notaria: "Juan Barrios Álvarez",
    protocolo: "2457",
    vendedor: "VERDE IBERIA PROPERTIES, S.L.U.",
    precio: 325000,
    ref_catastral: "1188507DD8718G0001KP",
    valor_catastral: null,
    superficie_m2: 288,
    anio_construccion: null,
    estado: "Ocupada (ejecución hipotecaria)",
    cargas: "Libre de cargas",
  },
  E65: {
    nombre: "Elfo 65",
    ciudad: "Madrid",
    fecha_firma: "21/11/2025",
    notaria: "Juan Barrios Álvarez",
    protocolo: "2731",
    vendedor: "BUILDINGCENTER, S.A.U.",
    precio: 165000,
    ref_catastral: "4863602VK4746D0015FM",
    valor_catastral: null,
    superficie_m2: 58.76,
    anio_construccion: null,
    estado: "Arrendada",
    cargas: "Libre de cargas",
  },
  M1: {
    nombre: "Molino 1",
    ciudad: "Villanueva de la Cañada",
    fecha_firma: "21/11/2025",
    notaria: "Juan Barrios Álvarez",
    protocolo: "2731",
    vendedor: "BUILDINGCENTER, S.A.U.",
    precio: 179000,
    ref_catastral: "5181701VK1758S0009BT",
    valor_catastral: null,
    superficie_m2: 78.22,
    anio_construccion: null,
    estado: "Arrendada",
    cargas: "Libre de cargas",
  },
  AG55: {
    nombre: "Alfonso Gómez 55",
    ciudad: "Madrid",
    fecha_firma: "21/11/2025",
    notaria: "Juan Barrios Álvarez",
    protocolo: "2731",
    vendedor: "BUILDINGCENTER, S.A.U.",
    precio: 279650,
    ref_catastral: "7063707VK4776C0145YR",
    valor_catastral: null,
    superficie_m2: 82.80,
    anio_construccion: null,
    estado: "Arrendada",
    cargas: "Libre de cargas",
  },
};

// Precio total de adquisición (solo precios de escritura, sin gastos)
export const TOTAL_PRECIO_ADQUISICION = Object.values(ESCRITURAS).reduce(
  (sum, e) => sum + e.precio,
  0
);

// Lista de códigos de activos inmobiliarios (sin AN)
export const ACTIVOS_INMUEBLES = Object.keys(ESCRITURAS);
